### ISSUE TITLE
Missing data for 60633

### ISSUE THREAD

**Issue by derekeder** [smartchicago/chicago-atlas#175]
60633 is listed on the [places page](http://chicago-atlas-staging.herokuapp.com/places#zipcode), but no data is available on the map, and the [detail page](http://chicago-atlas-staging.herokuapp.com/place/60633) returns an error (probably because no data).

@robparal pointed this out and noticed:
- Zip 60827: the population data is actually the sum of zip 60827 and zip 60633
- Zip 60633: has no data in the Atlas (but does show resources)

Before I merge, @JamyiaClark could you confirm that the data you have for zipcode 60633 is merged in to 60827?

**Comment by easherma** [comment]
FYI, as is community_areas.geojson is technically not valid geojson
