### ISSUE TITLE
conflation of USPS zip codes and US Census zip code tabulation areas (ZCTAs)

### ISSUE THREAD

**Issue by derekeder** [smartchicago/chicago-atlas#176]
@robparal pointed out that the zip codes he has been working with to do data aggregation from the US Census are different than the zip codes on the Health Atlas. 
## US Postal Service (USPS) Zip Codes

The Health Atlas uses [zip code boundaries from the City of Chicago data portal](https://data.cityofchicago.org/Facilities-Geographic-Boundaries/Boundaries-ZIP-Codes-KML/syyx-k68t), which are the [US Postal Service (USPS) zip codes](http://en.wikipedia.org/wiki/ZIP_code).

![screen shot 2014-04-29 at 9 57 21 am](https://cloud.githubusercontent.com/assets/919583/2830429/9591b93e-cfae-11e3-8dfb-9f3fe697207a.png)
## US Census Zip Code Tabulation Areas (ZCTAs)

The US Census also has their own 'zip code-like' areas called [Zip Code Tabulation Areas](http://en.wikipedia.org/wiki/ZIP_Code_Tabulation_Area). They are comprised of census tracts for the purposes of aggregating census demographics.
![screen shot 2014-04-28 at 2 52 53 pm](https://cloud.githubusercontent.com/assets/919583/2830461/de1104bc-cfae-11e3-978c-749773f79ca5.png)
## We are likely using both

We need to do an audit of our zip code data, as I believe we are using these two zip code boundaries interchangeably. Here's my assessment:
- **Health Atlas zipcode boundaries** using USPS Zip Codes
- **CHITREC data** this comes from patient records, so the likely boundaries are what people use as their zip code address, which are the USPS Zip Codes
- **Chicago Dept of Public Health (chronic diseases)** Unknown, but it is likely US Census ZCTA's
- **Population demographics** very likely US Census ZCTAs as it would be very difficult to roll up these demographics otherwise

Moving forward, we should pick one kind of zip code boundary and use it consistently. There are arguments for both.
- when someone tells you their zip code, it is the USPS zip code. this is useful for data coming from patient records and businesses
- if we want to show demographic information, the US Census is only able to do so with ZCTAs as they are derived from census tracts and don't change over time as much as USPS zip codes

**Comment by janahirschtick** [comment]
Hi guys,
I wanted to chime in here since I have been facing this issue for some time and haven't found a good solution yet. I'm an epidemiologist and often need to calculate disease rates and hospitalizations by community (zip). As you mentioned above, data on hospitalizations is provided by USPS zip code. However, I need population data for the denominator to calculate a rate. I was using zip code population estimates from MCIC for a while but these data are now outdated and didn't include other demographic variables of interest for modeling. So, currently I'm planning to use census ZCTA data for the denominator. 

I believe this is what CDPH does as well for their hospitalization rates, after making minor adjustments and aggregating the numerator data for a few small zip codes. I'm planning on making a note about this limitation but can't figure out any other way around it. If you have any suggestions please let me know!

Thanks,
Jana

**Comment by robparal** [comment]
Hi Jana: An issue is the extent to which the Zip Code Tabulations Areas of
the Census Bureau differ from the postal zip codes.  They do, but the
difference may be minor enough to not matter substantially, depending on
your tolerance for inexactitude.  I once overlayed ZCTAs over postal zips
in Chicago and looked very carefully at them. My memory is that the postal
zips are drawn in a way that you could not recreate them with blocks; they
do not strictly follow block boundaries.

Rob

On Tue, May 19, 2015 at 12:00 PM, janahirschtick <notifications@github.com>
wrote:

> Hi guys,
> I wanted to chime in here since I have been facing this issue for some
> time and haven't found a good solution yet. I'm an epidemiologist and often
> need to calculate disease rates and hospitalizations by community (zip). As
> you mentioned above, data on hospitalizations is provided by USPS zip code.
> However, I need population data for the denominator to calculate a rate. I
> was using zip code population estimates from MCIC for a while but these
> data are now outdated and didn't include other demographic variables of
> interest for modeling. So, currently I'm planning to use census ZCTA data
> for the denominator.
>
> I believe this is what CDPH does as well for their hospitalization rates,
> after making minor adjustments and aggregating the numerator data for a few
> small zip codes. I'm planning on making a note about this limitation but
> can't figure out any other way around it. If you have any suggestions
> please let me know!
>
> Thanks,
> Jana
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartchicago/chicago-atlas/issues/176#issuecomment-103591170>
> .
>



-- 
Rob Paral
773-609-4510
www.robparal.com
robparal.blogspot.com
<http://www.linkedin.com/in/robparal>

**Comment by janahirschtick** [comment]
Thanks Rob. Yes, I know zips and ZCTAs don't align perfectly, but I haven't figured out a way to get around this. Perhaps I will try overlaying them as well to take a closer look so I can discuss it in my limitations. 

Jana

**Comment by robparal** [comment]
​Good luck Jana and let us know if we might be able to help.
Rob​

On Wed, May 20, 2015 at 9:53 AM, janahirschtick <notifications@github.com>
wrote:

> Thanks Rob. Yes, I know zips and ZCTAs don't align perfectly, but I
> haven't figured out a way to get around this. Perhaps I will try overlaying
> them as well to take a closer look so I can discuss it in my limitations.
>
> Jana
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartchicago/chicago-atlas/issues/176#issuecomment-103916230>
> .
>



-- 
Rob Paral
773-609-4510
www.robparal.com
robparal.blogspot.com
<http://www.linkedin.com/in/robparal>
