### ISSUE TITLE
import and display Divvy data

### ISSUE THREAD

**Issue by derekeder** [smartchicago/chicago-atlas#188]
Related to #152

**Comment by derekeder** [comment]
doing a little issue cleaning. mind un-assigning me from this one @smarziano ?

**Comment by smarziano** [comment]
Are you sure you don't want to import some Divvy data? Unassigned, @derekeder!

**Comment by derekeder** [comment]
not at this time 😛 
thanks @smarziano !

**Comment by derekeder** [comment]
oops didnt mean to close it! reopening
