### ISSUE TITLE
Add Hospital Service Areas

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#197]
From @robparal -- A presentation of these different service areas:
https://www.dropbox.com/s/1g2shw6ub73942p/Guide%20to%20Hospital%20Service%20Areas.pptx

and the PNG files:
https://www.dropbox.com/s/1hqvw7wmgc3qtsg/PNG%20files%20of%20hospital%20service%20areas.zip

**Comment by theandrewbriggs** [comment]
This is how the service areas will look:
![service-area](https://cloud.githubusercontent.com/assets/3439795/9360429/bd7225ea-465b-11e5-9262-db186714ef85.png)

They can also be a single shape (as opposed to broken up by zip code), though that will need to be handled by @robparal.

**Comment by robparal** [comment]
I like the way the service area looks with the zip codes. It gives some
more granularity.

On Wed, Aug 19, 2015 at 10:20 AM, Andrew Briggs <notifications@github.com>
wrote:

> This is how the service areas will look:
> [image: service-area]
> <https://cloud.githubusercontent.com/assets/3439795/9360429/bd7225ea-465b-11e5-9262-db186714ef85.png>
>
> They can also be a single shape (as opposed to broken up by zip code),
> though that will need to be handled by @robparal
> <https://github.com/robparal>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartchicago/chicago-atlas/issues/197#issuecomment-132636160>
> .
>



-- 
Rob Paral
773-609-4510
www.robparal.com
robparal.blogspot.com
<http://www.linkedin.com/in/robparal>

**Comment by KylaWilliams** [comment]
@robparal  We (me and @theandrewbriggs ) discussed adding the zip codes for clarity as well as a small piece of narrative under the map that states, "Northwestern Hospital serves the following community areas: ..." and those community areas are hyperlinked back to those specific pages.
