### ISSUE TITLE
Add index for terms/definitions

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#204]
We are interested in having an index of terms with easy-to-understand definitions.

This relates to #128.

**Comment by rynk** [comment]
Here are definitions I've derived from the Clinical Classifications Software schema of the Healthcare Cost and Utilization Project:
http://www.hcup-us.ahrq.gov/toolssoftware/ccs/CCSUsersGuide.pdf

Blood & Blood-Forming Organs: Includes anemia, bleeding, blood clots and white blood cell disorders.
Circulatory: Includes hypertension and heart conditions.
Congenital Anomalies: Birth defects.  
Digestive: Includes intestinal infection; disorders of teeth, jaws, mouth, esophagus or intestinal tract; appendicitis, hernias; other stomach and intestinal disorders; gallbladder, pancreatic, and liver disease.
Drug/Alcohol Related  
Endocrine, Nutritional/Metabolic, Immunity: Includes thyroid disease, diabetes, malnutrition, gout,  cystic fibrosis and obesity.
Genitourinary: Includes kidney disease, urinary tract infections, male and female genital disorders, non-malignant breast disease, contraception.
Ill-Defined  
Infectious/Parasitic: Includes bacterial and viral infections, blood poisoning, sexually transmitted infections, HIV and hepatitis.
Injury & Poisoning: Includes trauma-related disorders.
Muscoskeletal & Connective Tissue: Includes arthritis, back pain, osteoporosis; other bone, joint and muscle disorders; lupus and connective tissue disorders.   
Neoplasms: Cancer and non-malignant growth.
Nervous & Sensory: Includes central nervous system infection; hereditary, degenerative and other nervous system disorders; paralysis, headache, epilepsy and convulsions; coma and brain damage;
cataract, glaucoma and other eye disorders.
Not Coded  
Perinatal Period Related: Conditions affecting baby before and after childbirth.  
Pregnancy/Childbirth/Puerperium Related: Conditions affecting mother before and after childbirth. 
Psychotic & Intellectual  
Respiratory: Includes pneumonia, flu, tonsillitis, bronchitis, COPD and asthma.
Skin & Subcutaneous Tissue: Includes skin infection, bed sores, other skin disorders.




 


 206 - 209, 212	Other bone and musculoskeletal disease
210 - 211	Systemic lupus and connective tissues disorders
213 - 217	Congenital anomalies
219 - 224	Perinatal conditions
225 - 236, 239, 240, 244	Trauma-related disorders
237, 238	Complications of surgery or device
241 - 243	Poisoning by medical and non-medical substances
259	Residual codes
10, 254 - 258	Other care and screening
245 - 252	Symptoms
253	Allergic reactions
