### ISSUE TITLE
Bad link for CHITREC data on About page

### ISSUE THREAD

**Issue by shua123** [smartchicago/chicago-atlas#218]
On http://www.chicagohealthatlas.org/about , #2 under About the data 
"Anonymized clinical diagnosis information" links to https://github.com/smartchicago/chicago-atlas/raw/master/db/import/chitrec-data.csv which no longer exists.

It looks like CHITREC data is now in 2 files? (https://github.com/smartchicago/chicago-atlas/blob/master/db/import/chitrec_data_2006-2010.csv and https://github.com/smartchicago/chicago-atlas/blob/master/db/import/chitrec_data_2006-2012.csv )

**Comment by stevevance** [comment]
I just found the same problem as we're using this data for the [Slow Roll Chicago map](http://github.com/zorostang/chicago_bike_equity).
