### ISSUE TITLE
Physicians and Medicaid-Accepting Physicians by Community Area and Zip Code

### ISSUE THREAD

**Issue by robparal** [smartchicago/chicago-atlas#220]

**Comment by rynk** [comment]
Quick maps:
Medical practitioners: https://ry.cartodb.com/viz/d1dd80c0-074e-11e5-9e16-0e0c41326911/public_map
Medicaid accepted: https://ry.cartodb.com/viz/6450d7be-074e-11e5-bea8-0e853d047bba/public_map

**Comment by robparal** [comment]
The file https://drive.google.com/file/d/0B9vdVdII0XSCZTR1ZzNxR3FHcVk/view?usp=sharing
supercedes and replaces an earlier version that had been posted. I have clarified the labeling and code list, and have deleted unnecessary data and spreadsheets.

The files include the names, practice address, medical specialty and other items for all doctors, dentists and selected other health providers by Chicago community area and zip code.

--NPI_Chicago_only_CAs.xlsx are medical practitioners of all kinds as of May 2015 with the Chicago community area of their practice location.
--NPI_Chicago_only_ZCTAs_Rev_-5-28-15.xlsx are medical practitioners of all kinds as of May 2015 with the Chicago zip code of their practice location.
--NPI_HFS_CAs_Rev_-5-28-15.xlsx are medical practitioners as of May 2015 who have billed Medicaid in 2012,with Medicaid billing information with the Chicago community area of their practice location.
--NPI_HFS_ZCTAs_Rev_-5-28-15.xlsx are medical practitioners as of May 2015 who billed Medicaid in 2012,with Medicaid billing information with the Chicago zip code of their practice location.
