### ISSUE TITLE
Count of affordable resources per neighborhood not displayed on hover

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/chicago-atlas#221]
On the Affordable Resources page (http://www.chicagohealthatlas.org/map/affordable_resources#/?year=2015), when the user hovers over a neighborhood, the info window should display the number of resources. Currently it displays "Resources: undefined"

![screenshot 2015-05-27 14 38 37](https://cloud.githubusercontent.com/assets/100556/7845715/491e1286-047e-11e5-8d4b-c9250acbd024.png)

**Comment by theandrewbriggs** [comment]
The map works like it should in my dev environment, so the production server might be missing data or is showing older code. I'll look into those options when I get production access.

**Comment by theandrewbriggs** [comment]
This is fixed.
