### ISSUE TITLE
Hospitals Missing from List

### ISSUE THREAD

**Issue by KylaWilliams** [smartchicago/chicago-atlas#223]
Per Healthy Chicago Hospital Collaborative meeting today, not all of the Chicago hospitals are listed.

**Comment by robparal** [comment]
The hospitals we have are from Illinois Health Facilities and Services Review Board.  Did the Collaborative know who is missing and why?

**Comment by danxoneil** [comment]
@robparal did we ever figure out which were missing + why?

**Comment by robparal** [comment]
@danxoneil I haven't heard which hospitals were not included. I was not at the meeting when this was discussed.

**Comment by danxoneil** [comment]
Understood. Reopening so we can provide that info.

**Comment by rynk** [comment]
The IRS requires tax-exempt hospitals to define their service area. A Chicago Department of Public Health report includes service area are displayed with a community area overlay, not in the atlas. 

Three suburban hospitals are not in the atlas:

Advocate Christ Medical Center
4440 W. 95th St.
Oak Lawn, IL 60453
(708) 684-8000

Little Company of Mary Hospital
2800 W. 95th St. 
Evergreen Park, IL 60805
708-422-6200

Presence St. Francis Hospital
355 Ridge Ave.
Evanston, IL 60202
(847) 316-4000

Source: Maps pages 17-21 https://www.cityofchicago.org/content/dam/city/depts/cdph/statistics_and_reports/ChicagoHospitalsandACAReport2015

Rush University Medical Center identifies as a general hospital and a children's hospital, and should not be uncategorized.
https://www.rush.edu/about-us/overview-about-rush

RML Specialty Hospital Chicago is a long-term acute care hospital.
http://www.rmlspecialtyhospital.org/wp-content/uploads/2013/11/RML_CHNA_Report_Chicago_FINAL_1309111.pdf

**Comment by robparal** [comment]
The hospitals we included in the atlas to date, at
http://www.chicagohealthatlas.org/hospitals, are only those that had a
Chicago address.

On Tue, Jul 28, 2015 at 11:53 AM, Stephen Rynkiewicz <
notifications@github.com> wrote:

> The IRS requires tax-exempt hospitals to define their service area. A
> Chicago Department of Public Health report includes service area are
> displayed with a community area overlay, not in the atlas.
>
> Three suburban hospitals are not in the atlas:
>
> Advocate Christ Medical Center
> 4440 W. 95th St.
> Oak Lawn, IL 60453
> (708) 684-8000
>
> Little Company of Mary Hospital
> 2800 W. 95th St.
> Evergreen Park, IL 60805
> 708-422-6200
>
> Presence St. Francis Hospital
> 355 Ridge Ave.
> Evanston, IL 60202
> (847) 316-4000
>
> Source: Maps pages 17-21
> https://www.cityofchicago.org/content/dam/city/depts/cdph/statistics_and_reports/ChicagoHospitalsandACAReport2015
>
> Rush University Medical Center identifies as a general hospital and a
> children's hospital, and should not be uncategorized.
> https://www.rush.edu/about-us/overview-about-rush
>
> RML Specialty Hospital Chicago is a long-term acute care hospital.
>
> http://www.rmlspecialtyhospital.org/wp-content/uploads/2013/11/RML_CHNA_Report_Chicago_FINAL_1309111.pdf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartchicago/chicago-atlas/issues/223#issuecomment-125677628>
> .
>



-- 
Rob Paral
773-609-4510
www.robparal.com
robparal.blogspot.com
<http://www.linkedin.com/in/robparal>

**Comment by KylaWilliams** [comment]
@robparal to send the three missing hopsitals in the corrected format to Andrew.  Kyla to query Hospital Collaborative to ensure all hospitals are listed with the inclusion of the three.

**Comment by robparal** [comment]
Per Steve R., there were 3 hospitals based in the suburbs that include a
portion of Chicago in their service area.
These are:
Advocate Christ Medical Center, Oak Lawn, IL
Little Company of Mary, Evergreen Park, IL
Presence Saint Francis, Evanston, IL

I attach 2013 data for these hospitals. Steve, can you call me about this?

Thanks,

Rob

However, the


On Wed, Aug 5, 2015 at 12:57 PM, KylaWilliams <notifications@github.com>
wrote:

> @robparal <https://github.com/robparal> to send the three missing
> hopsitals in the corrected format to Andrew. Kyla to query Hospital
> Collaborative to ensure all hospitals are listed with the inclusion of the
> three.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartchicago/chicago-atlas/issues/223#issuecomment-128091648>
> .
>



-- 
Rob Paral
773-609-4510
www.robparal.com
robparal.blogspot.com
<http://www.linkedin.com/in/robparal>

**Comment by robparal** [comment]
Per my conversation with Andrew, here are the three missing hospitals with
*2012* data to match the data we already have up on the site.

Rob


On Tue, Aug 11, 2015 at 4:26 PM, Rob Paral <rob@robparal.com> wrote:

> Per Steve R., there were 3 hospitals based in the suburbs that include a
> portion of Chicago in their service area.
> These are:
> Advocate Christ Medical Center, Oak Lawn, IL
> Little Company of Mary, Evergreen Park, IL
> Presence Saint Francis, Evanston, IL
>
> I attach 2013 data for these hospitals. Steve, can you call me about this?
>
> Thanks,
>
> Rob
>
> However, the
>
>
> On Wed, Aug 5, 2015 at 12:57 PM, KylaWilliams <notifications@github.com>
> wrote:
>
>> @robparal <https://github.com/robparal> to send the three missing
>> hopsitals in the corrected format to Andrew. Kyla to query Hospital
>> Collaborative to ensure all hospitals are listed with the inclusion of the
>> three.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/smartchicago/chicago-atlas/issues/223#issuecomment-128091648>
>> .
>>
>
>
>
> --
> Rob Paral
> 773-609-4510
> www.robparal.com
> robparal.blogspot.com
> <http://www.linkedin.com/in/robparal>
>
>
>
>


-- 
Rob Paral
773-609-4510
www.robparal.com
robparal.blogspot.com
<http://www.linkedin.com/in/robparal>
