### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by KylaWilliams** [smartchicago/chicago-atlas#238]
@theandrewbriggs Adding Social Media Links to Hospital Pages.  Focusing only on FB and Twitter, maybe a FB button and then the Hospital's Twitter feed depending on space.

**Comment by theandrewbriggs** [comment]
@KylaWilliams I've looked a bit into embedding stuff and it's not too tough, were you going to get a master list together of the pages/feeds from the hospitals that they wanted displayed? Or should I just grab what I can find on their sites?

**Comment by KylaWilliams** [comment]
@theandrewbriggs I have a Master List via wufoo.  We sent it out last week and I will follow up with HDA to see who we haven't received a response from.

**Comment by theandrewbriggs** [comment]
Here's a couple sample images of what social links could look like:

a) We could include the built-in social links on the sidebar with the map:
![screen shot 2015-09-17 at 17 35 39](https://cloud.githubusercontent.com/assets/3439795/10001706/afd55246-6068-11e5-9162-b858562e082e.png)

b) We could add them just below the name of the hospital:
![screen shot 2015-09-17 at 17 08 43](https://cloud.githubusercontent.com/assets/3439795/10001719/c726e5c2-6068-11e5-8a30-74da0721b2b1.png)

c) Embedding the Twitter timeline - Given the decision that we should build the site around community leaders looking to get broad data and not for the average citizen, I don't think embedding the timeline is prudent. It's a lot of extra information and including the timeline (even a very small one) pushes the important data content off the page (as it is, the user has to scroll down past the page break to get to the data on a typical screen). I don't think this is the way we want to go:
![screen shot 2015-09-18 at 11 09 51](https://cloud.githubusercontent.com/assets/3439795/10001849/5cc10af4-6069-11e5-8cb1-556a724d4ef6.png)

d) Icons. These could go in any of the above places but I think they make the most sense with the contact information:
![screen shot 2015-09-21 at 13 54 41](https://cloud.githubusercontent.com/assets/3439795/10001867/83fb5a16-6069-11e5-94af-64754a607257.png) 

Or we could use plain, unadorned links.

**Comment by robparal** [comment]
My vote is the first option.
Thanks,
Rob

On Mon, Sep 21, 2015 at 2:03 PM, Andrew Briggs <notifications@github.com>
wrote:

> Here's a couple sample images of what social links could look like:
>
> a) We could include the built-in social links on the sidebar with the map:
> [image: screen shot 2015-09-17 at 17 35 39]
> <https://cloud.githubusercontent.com/assets/3439795/10001706/afd55246-6068-11e5-9162-b858562e082e.png>
>
> b) We could add them just below the name of the hospital:
> [image: screen shot 2015-09-17 at 17 08 43]
> <https://cloud.githubusercontent.com/assets/3439795/10001719/c726e5c2-6068-11e5-8a30-74da0721b2b1.png>
>
> c) Embedding the Twitter timeline - Given the decision that we should
> build the site around community leaders looking to get broad data and not
> for the average citizen, I don't think embedding the timeline is prudent.
> It's a lot of extra information and including the timeline (even a very
> small one) pushes the important data content off the page (as it is, the
> user has to scroll down past the page break to get to the data on a typical
> screen). I don't think this is the way we want to go:
> [image: screen shot 2015-09-18 at 11 09 51]
> <https://cloud.githubusercontent.com/assets/3439795/10001849/5cc10af4-6069-11e5-8cb1-556a724d4ef6.png>
>
> d) Icons. These could go in any of the above places but I think they make
> the most sense with the contact information:
> [image: screen shot 2015-09-21 at 13 54 41]
> <https://cloud.githubusercontent.com/assets/3439795/10001867/83fb5a16-6069-11e5-94af-64754a607257.png>
>
> Or we could use plain, unadorned links.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartchicago/chicago-atlas/issues/238#issuecomment-142078669>
> .
>



-- 
Rob Paral
773-609-4510
www.robparal.com
robparal.blogspot.com
<http://www.linkedin.com/in/robparal>
