### ISSUE TITLE
Hospital Admission tabs on main map missing metadata

### ISSUE THREAD

**Issue by theandrewbriggs** [smartchicago/chicago-atlas#255]
The Hospital Admissions tab is missing a header that explains the data as well as links to the data source and data download.

@robparal: Can you provide the necessary copy here and source? I'll take care of everything from there.

**Comment by robparal** [comment]
Hi Andrew: the hospital admissions data currently on the website should
have this source:

Source: Illinois Department of Public Health, hospital discharge data
derived from claim and encounter data submitted by Illinois facilities to
patients and public and private payors.

The data are at the link below, but that is the data as I delivered it,
including a transmittal memo that should not be made public.  But that data
needs to be posted somewhere for public access.

https://drive.google.com/folderview?id=0B9vdVdII0XSCUk1jVzdhLTE2bkE&usp=sharing



On Fri, Jan 29, 2016 at 11:14 AM, Andrew Briggs <notifications@github.com>
wrote:

> The Hospital Admissions tab is missing a header that explains the data as
> well as links to the data source and data download.
>
> @robparal <https://github.com/robparal>: Can you provide the necessary
> copy here and source? I'll take care of everything from there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartchicago/chicago-atlas/issues/255>.
>



-- 
Rob Paral
773-609-4510
www.robparal.com
<https://twitter.com/robparal>   <https://www.linkedin.com/in/robparal>
*Chicago Data Guy* blog <http://robparal.blogspot.com/>
