### ISSUE TITLE
Better map printing

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/chicago-atlas#256]
This is an item that came up in the Healthy Chicago Hospital Collaborative Data Workgroup Meeting on December 17, 2015. Perhaps members of the working group can expound here.

**Comment by evgelber** [comment]
I think they want a print button. The ability to embed and share is nice too. One member mentioned wanting to put maps in reports or presentations. For example, if you try to print the hospital page (or print to pdf), both the map and text don't look so nice.
