### ISSUE TITLE
[Healthy Chicago] Suggestion: Repeat or sticky header

### ISSUE THREAD

**Issue by shua123** [smartchicago/chicago-atlas#269]
For the Healthy Chicago 2.0 table, when you get towards the bottom it is easy to lose track of what each column represents. It might be a good idea to look at either repeating the column headers with each color section switch or have the column header row stick at the top as you scroll.

**Comment by smarziano** [comment]
This issue exists with the beta website. Our community stakeholder testers consistently recommended the same enhancement.

**Comment by jcrichlow** [comment]
@parrolabs will migrate LOEs from Asana

**Comment by jcrichlow** [comment]
LOE: < 1 hour
