### ISSUE TITLE
Homepage: Update hero image

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#273]
The hero image was described by our community stakeholders as "dark" and only representative as downtown Chicago. The recommendation is to upgrade this image to be brighter, more colorful, and representative of Chicago communities.

**Comment by jcrichlow** [comment]
@RaedMan and @ldurr, could you upload the final hero and icon images to this case by EOD Monday 5/15 so @parrolabs can implement the UI changes

**Comment by RaedMan** [comment]
I will be posting URLs of photos I have chosen from CCT Flikr account here for everyone to review and approve: https://www.flickr.com/photos/chitrust

**Comment by jcrichlow** [comment]
@parrolabs will migrate LOEs from Asana

**Comment by jcrichlow** [comment]
LOE: ~ 1 hour
