### ISSUE TITLE
About: Highlight Sprague support and add logo

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#277]
Related to #276 

The Otho S. A. Sprague Memorial Institute should be highlighted on the /about page. Currently, Sprague's support appears less in one line– "The project is funded by the Otho S. A. Sprague Memorial Institute"– under the Smart Chicago logo and section. Recommendation is to pull this information out in its own section and to add the Sprague's logo.

**Comment by jcrichlow** [comment]
Hi @smarziano can you add the "enhancement" label to this issue?
