### ISSUE TITLE
Topics: Community area data responsive to year drop-down?

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#281]
A question came up in our recent usability test related to the indicator topic page "Teen Birth Rate." It appears when you toggle from "City Wide" to "Community area" and then change the year in the drop-down, the data for each community area does not change. 

The questions that came up were: 
- Is this is correct, and the data has stayed the same over the years? Or are there minor changes in data that we are not observing?
- Is this community area data specific only to one year and, therefore, the user should not be able to change the year?
- Do we have community area data for different years, and there is currently a bug causing it not to display?

**Comment by jcrichlow** [comment]
Hi @smarziano can you add the "bug" label to this issue?

**Comment by smarziano** [comment]
Adding the year to the chart really clarifies this issue. Closing!
<img width="946" alt="screen shot 2017-10-19 at 1 09 14 pm" src="https://user-images.githubusercontent.com/5550969/31786617-bd57ce64-b4ce-11e7-9f43-4494990c49c0.png">
