### ISSUE TITLE
Topics: Race/Ethnicity labels overlap on disparities graph

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#283]
Similar to issue #279, we are seeing that the race/ethnicity labels on the disparities chart are overlapping making this text difficult to read. 

Below is a screenshot from my MacBook Pro 13-inch and this would be an even bigger issue viewing on smaller screens.
<img width="875" alt="screen shot 2017-04-30 at 10 16 27 am" src="https://cloud.githubusercontent.com/assets/5550969/25565547/4f6954f8-2d8e-11e7-83de-3bdc1b5925b3.png">

**Comment by parrolabs** [comment]
Is this equal to #279?

**Comment by smarziano** [comment]
@parrolabs This is the same problem across issues but on different pages and with different graphs. This issue relates to the indicator pages, #279 is specifically on the community area profile pages.

**Comment by smarziano** [comment]
This has been improved. Closing issue.

<img width="875" alt="screen shot 2017-10-19 at 1 12 00 pm" src="https://user-images.githubusercontent.com/5550969/31786758-248e21b4-b4cf-11e7-99f4-78c20d15e675.png">
