### ISSUE TITLE
Indicator // Summary // Understanding the Measure

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#286]
Tracked in Asana: https://app.asana.com/0/270273090137879/335457084728568

There are incorrect headings ("Youth fruit and vegetable consumption - Weighted Number" and "Youth fruit and vegetable consumption - Weighted Percent") listed under the "Understanding the measure" section for the following indicators:

- Bullying
- School fights
- School safety
- Youth condom use
- Youth depression

<img width="938" alt="screen shot 2017-04-30 at 10 46 47 am" src="https://cloud.githubusercontent.com/assets/5550969/25565716/56c68d0c-2d92-11e7-82c7-9b56bf3b661b.png">

**Comment by jcrichlow** [comment]
@parrolabs, i'm testing out if this message is also created in asana.

**Comment by smarziano** [comment]
I checked a few indicators and this no longer appears to be a problem. Closing issue!
