### ISSUE TITLE
Topics: Add broader context for datasets

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#295]
When users select an indicator (for example: /youth-smoking), some of our community stakeholder testers thought that there was too much information or the data was "overwhelming" at first. Others felt that a broader snapshot was missing and that the first pieces of data listed did not give a clear picture of this dataset in context.

Looking at youth smoking as an example– the first piece of data users see is "sexual identity" related. What some users expected to see was citywide data first, and then to drill down either by race, sexual identity, gender or even community. One tester mentioned that he would like to see a short narrative about the dataset and it's context underneath the page's header.

**Comment by jcrichlow** [comment]
Close case as breakdowns of issue already exist
