### ISSUE TITLE
Topics: Sub-heading arrows do not change on collapse 

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#296]
When a user clicks on a sub-heading, like "Community Safety" in the screenshot below, the small red arrow does not change. This behaves differently than when collapsing the broader heading, "Social and Economic Factors."

<img width="557" alt="screen shot 2017-05-01 at 1 30 54 pm" src="https://cloud.githubusercontent.com/assets/5550969/25589480/6b9a0ffc-2e72-11e7-807b-f3951e73190f.png">

**Comment by jcrichlow** [comment]
@parrolabs, please add LOE in Asana

**Comment by smarziano** [comment]
This has been updated. Closing issue.
