### ISSUE TITLE
Resources: Clicking on resource name unexpectedly leads to external website

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#304]
During our community stakeholder usability test, testers were surprised that clicking on a resource name would lead to an external website. Testers either expected to see expanded information or for the corresponding map point to be highlighted (#301).

In addition, sometimes if a resource does not have a link associated with it, clicking on the resource name will lead to a blank page (about:blank).

Suggestion is to add the website url so the user can click on the website if they want to go to the organization's specific page.

**Comment by jcrichlow** [comment]
Hi @smarziano can you add the "enhancement" label to this issue?

**Comment by smarziano** [comment]
Website addresses have been removed from the resources. Therefore, this is no longer an issue.
