### ISSUE TITLE
Groups of zip codes were confusing

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#311]
A few community stakeholder testers who viewed the zip codes list thought that it was confusing to have groups of zip codes on the site and was not sure why that was or how those groups could be used. 

For example: https://cha-front-test.herokuapp.com/zip-codes/6761 or https://cha-front-test.herokuapp.com/zip-codes/60622

**Comment by jcrichlow** [comment]
Hi @smarziano can you add the "enhancement" label to this issue?

**Comment by jcrichlow** [comment]
@parrolabs will migrate LOEs from Asana

**Comment by jcrichlow** [comment]
LOE: Discovery session needed

**Comment by smarziano** [comment]
This has been addressed. Closing.
