### ISSUE TITLE
Add or repeat data's unit of measurements

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-atlas#314]
During our community stakeholder usability testing, we heard questions about the units of measurement on all of the pages (Healthy Chicago, indicator pages, and community area pages). Even with the "Understanding the Measure" information on the indicator pages about weighted numbers, testers had questions about the unit of measurements. Therefore, as much as possible, units of measurement should be added in the data charts to make it clearer for users to understand the numbers they are reviewing.

**Comment by jcrichlow** [comment]
Hi @smarziano can you add the "bug" label to this issue?

**Comment by jcrichlow** [comment]
Kingsley will be verifying these data and confirming solutions in the content matrix
