### ISSUE TITLE
Add MAPSCorps Logo to Partners Page

### ISSUE THREAD

**Issue by RaedMan** [smartchicago/chicago-atlas#349]
![15mapscorps-navy pink](https://user-images.githubusercontent.com/3673571/31954857-49a53d30-b8ac-11e7-8656-66cddbf6cb9f.jpg)

**Comment by RaedMan** [comment]
Add their summary under logo:

MAPSCorps is a nonprofit organization that provides urban youth with meaningful employment and STEM (Science-Technology-Engineering-Math) training opportunities through a technology-based community asset mapping program. Our mission is to train youth to produce high-quality data about community assets that everyone can use to improve the human condition.

**Comment by knweaver** [comment]
Generally, we need to be able to update text and images/links on About page to add/remove partners, etc.

**Comment by RaedMan** [comment]
@knweaver I'll open a new issue for your comment to close this issue.
